DROP DATABASE IF EXISTS employee_d;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  deparment_name VARCHAR(30) NOT NULL,
  department_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE role (	
	job_title VARCHAR(30) NOT NULL,
  role_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  department_role VARCHAR(30) NOT NULL,
  salary DECIMAL,
 
);

CREATE TABLE employee (
  employee_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  job_title INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  department_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  salary DECIMAL,
  reporting_manager VARCHAR(30) NOT NULL,
    );

