DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  deparment_name VARCHAR(30) NOT NULL,
  department_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE role (	
  role_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	job_title VARCHAR(30) NOT NULL,
  salary DECIMAL,
  department_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
 
);

CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  manager_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  reporting_manager VARCHAR(30) NOT NULL
  );

